import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import sys
import os

# --- Unified Engine Integration ---
sys.path.append(os.path.join(os.path.dirname(__file__), "..", "core"))
try:
    from ProtorealEngine import (
        AgenticFrame, ProtorealSynthesis, ProtorealElement,
        calculate_standard_resonance, monster_stitch, get_engine_status
    )
    ENGINE_AVAILABLE = True
except ImportError:
    ENGINE_AVAILABLE = False

st.set_page_config(page_title="Monster Lattice | 𝕌", page_icon="🧬", layout="wide")

# --- Premium CSS ---
st.markdown(r"""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');
    .main { background-color: #0a0c10; }
    h1, h2, h3 { font-family: 'Inter', sans-serif !important; color: #e8eaf0 !important; }
    .stMarkdown p { font-family: 'Inter', sans-serif; color: #b0b8c8; }
    .monster-card {
        background: linear-gradient(135deg, rgba(255, 102, 255, 0.05), rgba(0, 0, 0, 0));
        border: 1px solid rgba(255, 102, 255, 0.12);
        border-radius: 16px; padding: 24px; margin: 16px 0;
    }
</style>
""", unsafe_allow_html=True)

st.title("🧬 Monster Lattice & Hodge Helicity")
st.markdown(r"""
Mapping the **Order-24 Monster Horizon** (Leech Lattice) and the stable **Hodge Cycles** generated by higher-order hyperoperations.
""")

if ENGINE_AVAILABLE:
    status = get_engine_status()
    st.sidebar.success(f"Engine: {status['Software State']}")
    st.sidebar.info(f"Monster Horizon: N=24")
    st.sidebar.caption(f"Curvature (κ): -1")

st.markdown("---")

# ════════════════════════════════════════════════════
# MONSTER HORIZON & HYPEROPERATIONS
# ════════════════════════════════════════════════════

col1, col2 = st.columns([2, 1])

with col1:
    st.subheader("🌀 The Hodge Cycle (N=24)")
    st.markdown(r"Visualizing the helicity of the manifold at the Total Phase Collapse.")
    
    # Generate a Hodge Helicity Cycle (Twisted Helix/Torus)
    t = np.linspace(0, 4*np.pi, 500)
    # Order-24 Twist
    n_monster = 24
    x = (2 + np.cos(t * n_monster / 4)) * np.cos(t)
    y = (2 + np.cos(t * n_monster / 4)) * np.sin(t)
    z = t / 2 + np.sin(t * n_monster / 4)
    
    fig_3d = go.Figure(data=[go.Scatter3d(
        x=x, y=y, z=z,
        mode='lines',
        line=dict(color=z, colorscale='Magma', width=6)
    )])
    
    fig_3d.update_layout(
        scene=dict(
            xaxis_title='ω-Real',
            yaxis_title='ι-Imag',
            zaxis_title='Helicity (H)',
            bgcolor='rgba(0,0,0,0)'
        ),
        template="plotly_dark",
        height=600,
        margin=dict(l=0, r=0, b=0, t=0)
    )
    st.plotly_chart(fig_3d, use_container_width=True)
    
    st.markdown(r"""
    **Understanding Hodge Helicity:**
    At the **$N=24$ Monster Horizon**, the manifold's curvature $\kappa = -1$ forces the transfinite path into a closed **Hodge Cycle**. The "twisting" you see is the **Helicity**, a quantized topological invariant proven in `MonsterLattice.lean`. This cycle represents the stable energy state where prime resonance and zeta-zeros achieve perfect symmetry.
    """)

with col2:
    st.subheader("⚛️ Hyperoperation Phasing")
    st.markdown("Select the level of topological thrust:")
    
    phase = st.select_slider(
        "Hyper-Phase Level",
        options=["Addition", "Multiplication", "Exponentiation", "Tetration"],
        value="Exponentiation"
    )
    
    st.markdown(f"**Current Engine: {phase}**")
    
    if phase == "Addition":
        st.latex(r"u_1 + u_2 \implies \text{Linear Drift}")
    elif phase == "Multiplication":
        st.latex(r"u_1 \cdot u_2 \implies \text{Cubic Attractor (Collatz)}")
    elif phase == "Exponentiation":
        st.latex(r"e^u \implies \text{Tri-modal Spiral (Zeta)}")
    else:
        st.latex(r"u \uparrow\uparrow n \implies \text{Monster Lattice Horizon}")
    
    st.markdown("---")
    
    # Helicity Metric
    h_val = -24.0 if phase == "Tetration" else -1.0
    st.metric("Hodge Helicity (H)", f"{h_val:.2f}", delta="-23.0" if phase == "Tetration" else "0")
    
    st.markdown(r"""
    <div class="monster-card">
        <div style="font-family: 'JetBrains Mono', monospace; color: #ff66ff; font-size: 0.85rem; margin-bottom: 10px;">
            HODGE STABILITY ANALYSIS
        </div>
        <div style="font-size: 0.95rem; color: #e8eaf0; line-height: 1.6;">
            At <b>Tetration-Phase</b>, the manifold achieves Total Phase Collapse. 
            The helicity is quantized to exactly <b>-24κ</b>, matching the symmetry of the Leech Lattice. 
            This is the point of maximal spectral stability.
        </div>
    </div>
    """, unsafe_allow_html=True)

st.markdown("---")
st.subheader("Unified Spectral-Monster Coupling")
t_vals = np.linspace(0.1, 10, 100)
fig_coupling = go.Figure()
fig_coupling.add_trace(go.Scatter(
    x=t_vals, y=t_vals**3, 
    name="Monster Expansion (Tetration)", 
    line=dict(color='#ff66ff', width=3)
))
fig_coupling.add_trace(go.Scatter(
    x=t_vals, y=np.sin(t_vals*n_monster/4), 
    name="Hodge Resonance Cycle", 
    line=dict(color='#00ffcc', width=3)
))
fig_coupling.update_layout(
    template="plotly_dark",
    paper_bgcolor='rgba(0,0,0,0)',
    plot_bgcolor='rgba(0,0,0,0)',
    xaxis_title="Manifold Depth (N)",
    yaxis_title="Phase Torsion",
    legend=dict(x=0.02, y=0.98)
)
st.plotly_chart(fig_coupling, use_container_width=True)

st.markdown("---")
st.markdown("#### **Next Step: Spectral Topography**")
st.markdown(r"""
Now that the **Monster Lattice** is formalized, we project these Hodge cycles into 
global phase-space to observe the **Leech Lattice Resonance**.
""")
if st.button("🛰️ Deploy Monster Radar"):
    st.switch_page("pages/1_Spectral_Topography.py")
